### ISSUE TITLE
Any chance at a release?

### ISSUE THREAD

**Issue by bcarrell** [ring-clojure/ring-codec#13]
Currently bashing my head against an issue that appears to have been solved by https://github.com/ring-clojure/ring-codec/pull/8 last year.

Also, you mentioned releasing a `1.0.1` version [here](https://github.com/ring-clojure/ring/issues/243#issuecomment-200541817) which would include that.

So, any chance at one?  :pray:

**Comment by weavejester** [comment]
Sorry, 1.0.1 keeps slipping my mind. I'll sort it out now.

**Comment by bcarrell** [comment]
No problem!  Thanks!!

**Comment by weavejester** [comment]
Released. Sorry for the delay!
