### ISSUE TITLE
Extending FormEncodeable to nil

### ISSUE THREAD

**Issue by boechat107** [ring-clojure/ring-codec#17]
Hey!

Would it make sense to extend `FormEncodeable` ([here](https://github.com/ring-clojure/ring-codec/blob/master/src/ring/util/codec.clj#L84)) to `nil` values? I got thinking about it when I tried to mock some requests with malformed values.

**Comment by weavejester** [comment]
What would `nil` be encoded to? A blank string?

**Comment by boechat107** [comment]
Yes, exactly!

```clj
{:a nil} => "a="
```

**Comment by boechat107** [comment]
If this makes sense, I could open a PR.

**Comment by weavejester** [comment]
Yes, I think it makes sense.

**Comment by boechat107** [comment]
Great, I'll open a PR soon.
