### ISSUE TITLE
Support form-encoding namespaced keywords

### ISSUE THREAD

**Issue by danielcompton** [ring-clojure/ring-codec#21]
We are using namespaced keywords in our query parameters, i.e. `?my.app%2fstatus=archived`. This works well from Swagger and from clients, but when we write a Ring Mock test like

```clj
(ring.mock.request/request :get "/queries/my-detail" {:my.app/status :archived})
```

the query string gets coerced to the namespaceless version:

```clj
(form-encode {:my.app/status :archived})
=> "status=%3Aarchived"
```

The root cause is the call to `name` on the key:

https://github.com/ring-clojure/ring-codec/blob/b01fcee9ffe35da85eeeb555ebecb24414d7d9a6/src/ring/util/codec.clj#L99

I don't know if there is a safe way to change this behaviour without massively breaking backwards compatibility. I wondered if you were interested in supporting this, perhaps with a dynamic var or other configuration option?

The alternative for us is to cast the keywords to a string ahead of time which works but loses the keywordy goodness.

**Comment by weavejester** [comment]
What about writing a function that transforms the keys into strings:

```clojure
(defn kw->str [kw]
  (str (namespace kw) "/" (name kw)))

(defn keys->strings [m]
  (into (empty m) (map (juxt kw->str str)) m))

(defn mock-request [method uri params]
  (ring.mock.request/request method uri (keys->strings params)))
```

**Comment by danielcompton** [comment]
Yep that's pretty much what we came up with (with some slight tweaks for unqualified keys). I could figure out what went wrong pretty quickly, but I wondered if this was something you wanted to look at fixing more generally. No problem if not, it's a pretty minor issue, easily worked around.

**Comment by weavejester** [comment]
I thought about adding a option map to `form-encode` or to `mock/request` to allow different key encoding schemes, but I don't think you'd save much code, a couple of lines at most. I think it's better to perform the transformation independently of the encoding function.

**Comment by danielcompton** [comment]
Cool, will close this for now then.
