### ISSUE TITLE
NumberFormatException from ring.util.codec/percent-decode

### ISSUE THREAD

**Issue by liwp** [ring-clojure/ring-codec#7]
Accessing URLs like

- http://example.com/%s/
- http://example.com/foo%sbar
- http://example.com/%XX

results in a `NumberFormatException`. This means that our app returns a `500` rather than the expected `404`.

Looks like the regex `#"%.."` [here](https://github.com/ring-clojure/ring-codec/blob/master/src/ring/util/codec.clj#L39-L43) should only match hex digits (`#"[0-9A-Fa-f]{2}"`), possibly.

The [spec](http://tools.ietf.org/html/rfc3986#section-2.4) (last paragraph of 2.4) seems to say that URLs like the ones above are not valid, because the `%` should be encoded as `%25` when it's not being used for percent-encoding.

So maybe the correct fix is to `catch` the exception and return a Client Error (e.g. `400 - Bad Request`)?

**Comment by jcf** [comment]
I'm creating a PR now.
